# Dashboard Service
apiVersion: v1
kind: Service
metadata:
  name: be-gateway
  namespace: hirehub
spec:
  selector:
    app: be-gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
